general:  # usually not written
    log:
        level: info
        filename: filename.log
        filemode: w
    outdir: .

data:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1/
    # options below are *exclusive*
    # users have a few options to specify which obs to use
    obs_ids: [42, 43]
    # obs_ids in a text file issued from previous complex filtering
    obs_file: obs.csv
    # obs_ids in a text file issued from previous complex filtering
    obs_filters:
      # list of filters applied as *reduce* to datastore
      - cone1: {frame: gal, lon: 42d, lat: 43d, radius: 3d}
      - cone2: gal 42d 43d 3d
      - time1: {start: 2019-12-01, stop: 2020-03-01}
      - time2: 2019-12-01 - 2020-03-01
      # TODO: should we offer more options?
      # Bruno: +1, Christoph: -1
      # - source: Crab 3d
      # - par: {name: ALT_PNT, min: 42d, max: 56d}

datasets:
    type: 3d # 1d
    stack: true
    background:
      method: reflected
      exclusion: exclusion.fits
    region: gal 42d 43d 3d
    containment_correction: true
    offset-max: 2.5d
    geom:
      wcs:
        # TODO: decide config format for SkyCoord
        skydir1: {frame: gal, lon: 83.633d, lat: 22.014d}
        # Custom format that is easy to parse with a regex
        skydir2: gal 83.633d 22.014d
        binsize: 0.1d
        # also binsize-irf / margin-irf
        fov: 7d 5d
      axes:
        # TODO: decide config format for energy MapAxis
        energy1: {min: 0.1, max: 10, unit: TeV, nbins: 30}
        # Custom format that is easy to parse with a regex
        energy2: 0.1 TeV - 10 TeV; 30 bins
        # also energy-true


fit:
    # TODO: decide config format for energy ranges
    fit_range: {min: 1 TeV, max: 100 TeV}
    # Custom format that is easy to parse with a regex
    fit_range2: 0.1 TeV - 100 TeV

flux_points:
    energy1: {min: 0.1, max: 10, unit: TeV, nbins: 30}
    energy2: 0.1 TeV - 10 TeV; 30 bins